import test from 'node:test';import assert from 'node:assert/strict';import {voiceScore,preferredVoice,bestNeuralVoice,getVoicesAsync,speakNeural} from '../src/speech.js';
test('natural English voices are preferred over robotic and non-English voices',()=>{const voices=[{name:'Fred',lang:'en-US',localService:true},{name:'Thomas',lang:'fr-FR'},{name:'Ava Premium',lang:'en-US',localService:true},{name:'Basic English',lang:'en-US',default:true}];assert.equal(preferredVoice(voices.filter(v=>voiceScore(v)>-1000),null).name,'Ava Premium');assert.ok(voiceScore(voices[0])<0);assert.ok(voiceScore(voices[1])<0);});
test('a parent-selected English voice wins when still installed',()=>{const voices=[{name:'Ava Premium',lang:'en-US'},{name:'Karen',lang:'en-AU'}];assert.equal(preferredVoice(voices,'Karen').name,'Karen');});
test('online neural voices beat local legacy voices for the First 100 speaker',()=>{const voices=[{name:'Microsoft David',lang:'en-US',localService:true},{name:'Samantha',lang:'en-US',localService:true},{name:'Google US English',lang:'en-US',localService:false}];assert.equal(bestNeuralVoice(voices).name,'Google US English');});
test('robotic voices are excluded from neural picks even when remote',()=>{assert.equal(bestNeuralVoice([{name:'Fred',lang:'en-US',localService:false}]),null);assert.equal(bestNeuralVoice([]),null);});
test('getVoicesAsync resolves immediately when voices are already loaded',async()=>{const voices=[{name:'Google US English',lang:'en-US'}];const synth={getVoices:()=>voices};assert.deepEqual(await getVoicesAsync(synth),voices);});
test('getVoicesAsync waits for voiceschanged when the list starts empty',async()=>{let current=[];let handler;const synth={getVoices:()=>current,addEventListener:(event,fn)=>{handler=fn;}};const pending=getVoicesAsync(synth);current=[{name:'Google US English',lang:'en-US'}];handler();assert.deepEqual(await pending,current);});
test('speakNeural picks the neural voice and keeps rate/pitch neutral',async()=>{const spoken=[];const synth={cancel(){},getVoices:()=>[{name:'Microsoft David',lang:'en-US',localService:true},{name:'Google US English',lang:'en-US',localService:false}],speak(u){spoken.push(u);}};class FakeUtterance{constructor(text){this.text=text;}}const ok=await speakNeural('Apple',{synth,Utterance:FakeUtterance});assert.equal(ok,true);assert.equal(spoken.length,1);assert.equal(spoken[0].text,'Apple');assert.equal(spoken[0].voice.name,'Google US English');assert.equal(spoken[0].rate,1);assert.equal(spoken[0].pitch,1);});
test('speakNeural returns false without a speech engine',async()=>{assert.equal(await speakNeural('Apple',{synth:null}),false);});
