import React from 'react';
import {Check,ArrowRight,RotateCcw} from 'lucide-react';
const fractionBar=(n,d,label)=> <div className="model-bar-block"><span>{label}</span><div className="fraction-bar" role="img" aria-label={`${n} of ${d} equal parts shaded`}>{Array.from({length:d},(_,i)=><span className={i<n?'filled':''} key={i}/>)}</div></div>;
export function Clock({hour,minute}){const radians=angle=>(angle-90)*Math.PI/180,hand=(angle,length)=>[100+length*Math.cos(radians(angle)),100+length*Math.sin(radians(angle))];const h=hand((hour%12)*30+minute/2,45),m=hand(minute*6,65);return <svg viewBox="0 0 200 200" className="clock-picture" role="img" aria-label="Analog clock with hour and minute hands"><circle cx="100" cy="100" r="90" fill="#fffdf4" stroke="#a8b996" strokeWidth="5"/>{Array.from({length:12},(_,i)=>{const n=i+1,p=hand(n*30,73);return <text key={n} x={p[0]} y={p[1]+5} textAnchor="middle">{n}</text>})}<path d={`M100 100L${h.join(' ')}`} stroke="#52745b" strokeWidth="7" strokeLinecap="round"/><path d={`M100 100L${m.join(' ')}`} stroke="#be916c" strokeWidth="4" strokeLinecap="round"/><circle cx="100" cy="100" r="6" fill="#52745b"/></svg>;}
function MiniRectangle({width,height}){return <div className="mini-rectangle"><span>{width} across</span><div className="tile-grid" style={{gridTemplateColumns:`repeat(${width},1fr)`,width:Math.min(width*20,240)}} role="img" aria-label={`${height} rows of ${width} squares`}>{Array.from({length:width*height},(_,i)=><span key={i}/>)}</div><span>{height} rows</span></div>;}
export function EnhancedVisual({q}){const m=q.model||{};
 switch(q.visual){
 case 'paint':case 'placeLine':return null;
 case 'expression':return <div className="expression-picture">{m.text|| (m.a!==undefined?`${m.a} ${m.operator||'×'} ${m.b} = ?`:m.h!==undefined?`${m.h*100} + ${m.t*10} + ${m.u} = ?`:q.skill==='equivalent'?`${m.n}/${m.d} = ?`:q.skill==='fractionDifference'?`${m.n}/${m.d} − ${m.m}/${m.d} = ?`:null)}</div>;
 case 'scene':return <div className="scene-picture"><span aria-hidden="true">{m.icon}</span><div>{m.items?.map((item,i)=><div key={i}><b>{item.value}</b><small>{item.label}</small></div>)}</div></div>;
 case 'sharing':return <div className="sharing-picture"><div className="sharing-total">{m.total} berries to share</div><div className="berry-pile" aria-hidden="true">{Array.from({length:m.total},(_,i)=><span key={i}>●</span>)}</div><div className="sharing-baskets">{Array.from({length:m.groups},(_,i)=><span key={i}>🧺<small>Friend {i+1}</small></span>)}</div></div>;
 case 'composite':{const cell=22,w=m.w1+m.w2,h=m.h1;return <svg className="composite-picture" viewBox={`0 0 ${w*cell+75} ${h*cell+70}`} role="img" aria-label={`Two joined rectangles: ${m.w1} by ${m.h1} and ${m.w2} by ${m.h2}`}><g transform="translate(35 30)">{Array.from({length:w*h},(_,i)=>{const x=i%w,y=Math.floor(i/w);if(x>=m.w1&&y<h-m.h2)return null;return <rect key={i} x={x*cell} y={y*cell} width={cell-2} height={cell-2} rx="2" fill={x<m.w1?'#adc395':'#e1bf8a'}/>})}<path d={`M${m.w1*cell-1} 0V${h*cell}`} stroke="#fffdf4" strokeWidth="3" strokeDasharray="5 4"/><text x={m.w1*cell/2} y="-10" textAnchor="middle">{m.w1}</text><text x="-17" y={h*cell/2} textAnchor="middle">{m.h1}</text><text x={(m.w1+m.w2/2)*cell} y={h*cell+22} textAnchor="middle">{m.w2}</text><text x={w*cell+17} y={(h-m.h2/2)*cell} textAnchor="middle">{m.h2}</text></g></svg>;}
 case 'rectanglePair':return <div className="rectangle-pair"><MiniRectangle width={m.a} height={m.b}/><span>{q.requireDifferent?'Reference garden':'↻'}</span>{!q.requireDifferent&&<MiniRectangle width={m.c} height={m.d}/>}</div>;
 case 'rectangle':return <svg viewBox="0 0 340 190" className="rectangle-picture" role="img" aria-label={`A rectangle with two sides of ${m.width} and two unknown sides`}><rect x="65" y="40" width="210" height="110" rx="4" fill="#e8eed9" stroke="#b59265" strokeWidth="3" strokeDasharray="7 4"/><text x="170" y="25" textAnchor="middle">{m.width}</text><text x="170" y="175" textAnchor="middle">{m.width}</text><text x="45" y="100">?</text><text x="290" y="100">?</text></svg>;
 case 'equivalentBars':return <div className="bars">{fractionBar(m.n,m.d,`${m.n}/${m.d}`)}{fractionBar(m.m,m.e,'Same whole, smaller pieces')}</div>;
 case 'unequalBars':return <div className="bars">{fractionBar(m.n,m.d,`${m.n}/${m.d}`)}{fractionBar(m.n,m.e,`${m.n}/${m.e}`)}<p>Both bars are one whole of the same size.</p></div>;
 case 'factTriangle':return <div className="fact-triangle"><b>{m.total}</b><div><span>{m.a}</span><span>{m.b}</span></div><small>Parts of one fact family</small></div>;
 case 'strategy':return <div className="strategy-picture"><MiniRectangle width={m.b} height={m.a}/><p>Can you turn it? Can you break it apart?</p></div>;
 case 'sequence':case 'numberCards':return <div className="sequence-picture">{m.values?.map((v,i)=><span key={i}>{v}</span>)}</div>;
 case 'placeTable':case 'placeBlocks':{return <div className="place-picture">{[['Hundreds',m.h,100],['Tens',m.t,10],['Ones',m.u,1]].map(([label,value,power])=><div key={label} className={m.highlight===power?'highlight-place':''}><small>{label}</small><b>{value}</b>{q.visual==='placeBlocks'&&<div className="base-blocks" aria-hidden="true">{Array.from({length:value},(_,i)=><span key={i} className={`base-${power}`}>{power===100?'▦':power===10?'▥':'▪'}</span>)}</div>}</div>)}</div>;}
 case 'vertical':return <div className="vertical-picture"><span>{m.a}</span><span>{m.operator} {m.b}</span><span>?</span></div>;
 case 'roundLine':{const pct=(m.num-m.lower)/(m.upper-m.lower)*100;return <div className="rounding-picture"><div><span>{m.lower}</span><span>{(m.lower+m.upper)/2}</span><span>{m.upper}</span></div><div className="rounding-track"><b style={{left:`${pct}%`}}>{m.num}</b></div></div>;}
 case 'clock':return <Clock hour={m.h} minute={m.minute}/>;
 case 'timeline':return <div className="timeline-picture"><span>{m.start}<small>Start</small></span><div>+ {m.duration} min<ArrowRight size={25}/></div><span>?<small>End</small></span></div>;
 case 'coins':return <div className="coins-picture">{m.coins.map((c,i)=><span key={i} className={c===1?'penny':''}><b>{c}¢</b><small>{{1:'Penny',5:'Nickel',10:'Dime',25:'Quarter'}[c]}</small></span>)}</div>;
 case 'ruler':return <svg viewBox="0 0 500 170" className="ruler-picture" role="img" aria-label={`A leaf from the ${m.start} centimeter mark to the ${m.end} centimeter mark`}><rect x="20" y="95" width="460" height="55" rx="5" fill="#eee0b5"/>{Array.from({length:15},(_,i)=><g key={i}><path d={`M${30+i*31} 95v16`} stroke="#968456"/><text x={30+i*31} y="135" textAnchor="middle">{i}</text></g>)}<path d={`M${30+m.start*31} 72Q${30+(m.start+m.end)/2*31} 0 ${30+m.end*31} 72Q${30+(m.start+m.end)/2*31} 117 ${30+m.start*31} 72Z`} fill="#a9c18d"/><path d={`M${30+m.start*31} 72H${30+m.end*31}`} stroke="#698851" strokeWidth="2"/><text x="450" y="165">cm</text></svg>;
 case 'chart':{const max=Math.max(...m.values);return <div className="bar-chart-picture" role="img" aria-label={m.names.map((n,i)=>`${n}: ${m.values[i]} votes`).join(', ')}><p>Favorite things · votes</p>{m.names.map((n,i)=><div key={n}><span>{n}</span><div className="chart-track"><b style={{width:`${m.values[i]/max*100}%`}}>{m.values[i]}</b></div></div>)}<small>Each bar shows a count of votes.</small></div>;}
 case 'dataTable':return <table className="data-picture"><caption>Favorite things · votes</caption><thead><tr><th>Category</th><th>Votes</th></tr></thead><tbody>{m.names.map((n,i)=><tr key={n}><th scope="row">{n}</th><td>{m.values[i]}</td></tr>)}</tbody></table>;
 default:return null;
 }
}
export function ActivityInput({q,solved,typed,setTyped,chosen,setChosen,painted,setPainted,point,setPoint,check}){
 if(q.type==='input')return <form className="typed-answer" onSubmit={e=>{e.preventDefault();if(typed.trim()&&!solved)check(typed);}}><label htmlFor="math-answer">Your answer{String(q.answer).includes('/')?' · a fraction like 2/3':''}</label><div><input id="math-answer" autoComplete="off" inputMode={String(q.answer).includes('/')?'text':'numeric'} value={typed} maxLength={30} disabled={solved} onChange={e=>setTyped(e.target.value)} placeholder={String(q.answer).includes('/')?'e.g. 2/3':'Type a number'}/><button className="primary" disabled={solved||!typed.trim()}>Check my answer <Check size={18}/></button></div></form>;
 if(q.type==='shade')return <div className="paint-activity"><div className="paint-pieces" style={{gridTemplateColumns:`repeat(${q.d},1fr)`}}>{Array.from({length:q.d},(_,i)=><button key={i} disabled={solved} className={painted.includes(i)?'painted':''} aria-pressed={painted.includes(i)} aria-label={`Piece ${i+1} of ${q.d}`} onClick={()=>setPainted(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i])}/>)}</div><p>{painted.length} of {q.d} pieces colored. Tap to paint or unpaint.</p><button className="primary" disabled={solved} onClick={()=>check(painted.length)}>Check my fraction <Check size={18}/></button></div>;
 if(q.type==='point')return <div className="point-activity"><div className="point-line" role="group" aria-label="Choose a number-line tick">{Array.from({length:q.d+1},(_,i)=><button key={i} disabled={solved} aria-pressed={point===i} aria-label={`Tick ${i} of ${q.d}`} className={point===i?'marked-point':''} onClick={()=>setPoint(i)}><span>{point===i?'●':'│'}</span><small>{i===0?'0':i===q.d?'1':''}</small></button>)}</div><p>Choose the tick where the fraction belongs.</p><button className="primary" disabled={solved||point===null} onClick={()=>check(point)}>Check my point <Check size={18}/></button></div>;
 if(['selectMany','order'].includes(q.type)){return <div className="selection-activity"><p>{q.type==='selectMany'?'More than one answer can match. Tap each one you choose.':'Tap the numbers in order. Tap a chosen number to remove it.'}</p><div className="answers">{q.choices.map(c=><button key={c} disabled={solved} className={chosen.includes(c)?'selected-clue':''} aria-pressed={chosen.includes(c)} onClick={()=>setChosen(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c])}>{c}{chosen.includes(c)&&(q.type==='order'?<small>{chosen.indexOf(c)+1}</small>:<Check size={18}/>)}</button>)}</div>{q.type==='order'&&<p className="order-preview">{chosen.join(' → ')||'Your order will appear here'}</p>}<button className="primary" disabled={solved||!chosen.length||q.type==='order'&&chosen.length!==q.choices.length} onClick={()=>check(chosen)}>Check my thinking <Check size={18}/></button></div>;}
 return null;
}
