const group = (id,name,tag,color,ink,icon,skills,activity,focus=true)=>({id,name,tag,color,ink,icon,skills,activity,focus});
export const worlds=[
 group('shapes','Shape Harbor','Notice, sort, and discover','#c1dce8','#366d88','⛵',['sides','properties','families','classify','rightAngles','parallelSides','symmetry','shapeClues'],'Hunt for four-sided shapes. Turn them around and explain which properties stay the same.'),
 group('area','Garden Island','Build, measure, and grow','#e8dfac','#827127','🌻',['area','perimeter','missingSide','areaVsPerimeter','compositeArea','sameArea','missingPerimeter','areaUnits'],'Build two paper gardens with the same area. Compare how much fence each needs.'),
 group('fractions','Fraction Forest','Explore equal parts in many ways','#c9dfc0','#537c49','🌳',['parts','numberLine','compare','fractionSum','shadeFraction','equivalent','unitFractions','compareNumerator','fractionDifference','fractionWhole','fractionPoint'],'Fold strips into halves, thirds, and quarters. Line up the ends to compare equal amounts.'),
 group('multiply','Mountain Makers','Group, split, share, and explain','#ddd3ed','#786291','⛰️',['array','split','missingFactor','divideShare','divideGroup','factFamilies','commutative','strategy','multiplyStory','patterns'],'Make an array of buttons. Show multiplication, division, and two ways to break it apart.'),
 group('numbers','Number Observatory','Keep your number powers bright','#ead4c5','#956e55','🔭',['placeValue','expanded','add','subtract','rounding','compareNumbers','numberPattern'],'Use three dice to build a number. Change one digit and explain how the value changes.',false),
 group('measure','Discovery River','Time, treasure, and real-life math','#c4e1dd','#417e77','🦦',['clock','elapsed','money','length','dataRead','dataCompare'],'Time a short walk, measure a toy, or survey your family and draw a small bar graph.',false),
];
const entries=[
 ['sides','Counting sides',1,[]],['properties','Shape properties',1,[]],['families','Shape families',2,['properties']],['classify','Naming shapes',1,[]],['rightAngles','Finding right angles',2,['properties']],['parallelSides','Parallel sides',2,['properties']],['symmetry','Lines of symmetry',2,['classify']],['shapeClues','Shape detective',3,['families','parallelSides']],
 ['area','Area in squares',1,[]],['perimeter','Around the boundary',1,[]],['missingSide','Missing side lengths',2,['area']],['areaVsPerimeter','Inside or around?',1,[]],['compositeArea','Putting areas together',3,['area','split']],['sameArea','Same area, new garden',2,['area']],['missingPerimeter','A missing fence length',3,['perimeter']],['areaUnits','Choosing area units',1,[]],
 ['parts','Equal parts',1,[]],['numberLine','Fractions on a line',1,[]],['compare','Comparing fractions',1,[]],['fractionSum','Adding equal parts',2,['parts']],['shadeFraction','Paint a fraction',1,[]],['equivalent','Different parts, same amount',2,['parts','numberLine']],['unitFractions','One equal piece',1,[]],['compareNumerator','Same pieces, different sizes',2,['unitFractions']],['fractionDifference','Taking equal parts away',2,['fractionSum']],['fractionWhole','Pieces to make a whole',2,['parts']],['fractionPoint','Place a fraction on the line',2,['numberLine']],
 ['array','Equal groups',1,[]],['split','Breaking apart products',2,['array']],['missingFactor','Missing factors',2,['array']],['divideShare','Sharing fairly',1,[]],['divideGroup','Making equal groups',2,['divideShare']],['factFamilies','Multiplication & division families',2,['array','divideShare']],['commutative','Turn the array',1,[]],['strategy','Show another way',3,['split','commutative']],['multiplyStory','Multiplication in stories',2,['array']],['patterns','Multiplication patterns',1,[]],
 ['placeValue','The value of a digit',1,[]],['expanded','Build a number',1,[]],['add','Add with a strategy',1,[]],['subtract','Subtract with a strategy',1,[]],['rounding','Nearby tens and hundreds',2,['placeValue']],['compareNumbers','Compare whole numbers',1,[]],['numberPattern','Find a number pattern',2,['add']],
 ['clock','Read the clock',1,[]],['elapsed','Time that passes',2,['clock']],['money','Count a coin collection',1,[]],['length','Measure from the start',1,[]],['dataRead','Read a bar graph',1,[]],['dataCompare','Compare graph categories',2,['dataRead']],
];
export const skillInfo=Object.fromEntries(entries.map(([id,label,tier,prerequisites])=>[id,{id,label,tier,prerequisites,world:worlds.find(w=>w.skills.includes(id)).id}]));
export const labels=Object.fromEntries(entries.map(([id,label])=>[id,label]));
export const skillCount=entries.length;
export function skillStage(progress,skill){const recent=progress.attempts.filter(a=>a.skill===skill).slice(-12),s=progress.skills[skill];if(!s?.total)return 'A fresh discovery';if(recent.length<4)return 'Getting to know it';const independent=recent.filter(a=>a.independent).length/recent.length;const reps=new Set(recent.filter(a=>a.independent).map(a=>a.representation));return independent>=.8&&reps.size>=2?'Making connections':independent>=.6?'Growing confidence':'Explore with a helping hand';}
export function availableSkills(progress,worldId){return worlds.filter(w=>!worldId||w.id===worldId).flatMap(w=>w.skills).filter(id=>{const info=skillInfo[id];return info.tier===1||info.prerequisites.every(p=>{const s=progress.skills[p];return s&&(s.independent>=3||s.total>=6&&s.supported>=3);});});}
export function practiceLevel(progress,skill){const recent=progress.attempts.filter(a=>a.skill===skill).slice(-12),s=progress.skills[skill];if(recent.length>=4){const rate=recent.filter(a=>a.independent).length/recent.length;if(rate<.5)return 1;if(recent.length>=8&&rate>=.8)return 3;if(rate>=.65)return 2;return 1;}return s&&s.independent>=8&&s.independent/s.total>.8?3:s&&s.independent>=3&&s.independent/s.total>.65?2:1;}
export function stickerCollection(progress){const completed=Object.values(progress.skills).reduce((n,s)=>n+s.independent+s.supported,0),explained=progress.attempts.filter(a=>a.reflection).length,covered=new Set(Object.keys(progress.skills).map(s=>skillInfo[s]?.world));return [
 {id:'first',icon:'🌱',name:'First little discovery',detail:'Explore one idea',earned:completed>=1},
 {id:'curious',icon:'🔎',name:'Curious explorer',detail:'Try five different skills',earned:Object.keys(progress.skills).length>=5},
 {id:'thinker',icon:'💬',name:'Thought sharer',detail:'Explain your thinking three times',earned:explained>=3},
 {id:'gardener',icon:'🌻',name:'Garden friend',detail:'Explore three garden skills',earned:worlds[1].skills.filter(s=>progress.skills[s]?.total).length>=3},
 {id:'fraction',icon:'🍃',name:'Piece by piece',detail:'Explore three fraction skills',earned:worlds[2].skills.filter(s=>progress.skills[s]?.total).length>=3},
 {id:'builder',icon:'🧱',name:'Pattern builder',detail:'Explore three multiplication skills',earned:worlds[3].skills.filter(s=>progress.skills[s]?.total).length>=3},
 {id:'traveler',icon:'🧭',name:'Island wanderer',detail:'Visit all six learning worlds',earned:covered.size>=6},
 {id:'connections',icon:'✨',name:'Making connections',detail:'Explore 25 ideas with or without help',earned:completed>=25},
 {id:'wonder',icon:'🦋',name:'Room to wonder',detail:'Explore 15 different skills',earned:Object.keys(progress.skills).length>=15},
 {id:'journeys',icon:'📔',name:'Adventure keeper',detail:'Keep five adventure memories',earned:progress.sessions.length>=5},
 ];}
