import React,{useEffect,useRef,useState} from 'react';
import {Volume2,ArrowRight,Heart,BarChart3,Home,Sparkles,Lightbulb,Paintbrush} from 'lucide-react';
import {PaintStudio} from './paint-studio.jsx';
import {englishVoices,preferredVoice,speakFriendly} from './speech.js';
import {initialPreschool,littleWorlds,littleLabels,nextLittle,recordLittle} from './preschool-engine.js';
const prizes=[['duck','🦆','Puddle Duck',20],['frog','🐸','Bouncy Frog',30],['dino','🦕','Leafy Dino',45],['lion','🦁','Sunny Lion',60],['rocket','🚀','Zoom Rocket',80],['dragon','🐲','Baby Dragon',100],['robot','🤖','Helpful Robot',120],['unicorn','🦄','Rainbow Unicorn',140],['whale','🐳','Bubble Whale',160],['owl','🦉','Night Owl',180],['monkey','🐵','Jungle Monkey',200],['castle','🏰','Story Castle',220]];
const solvedCount=p=>Object.values(p.skills).reduce((n,s)=>n+s.independent+s.supported,0),spent=p=>prizes.filter(x=>p.rewards?.owned?.includes(x[0])).reduce((n,x)=>n+x[3],0),stars=p=>Math.max(0,solvedCount(p)*5-spent(p));
function ProfileChooser({active,onSwitch}){return <label className="profile child-switcher"><span>{active==='pranav'?'P':'S'}</span><div><select aria-label="Choose child profile" value={active} onChange={e=>onSwitch(e.target.value)}><option value="shivani">Shivani</option><option value="pranav">Pranav</option></select><small>{active==='pranav'?'Little learner':'Curious explorer'}</small></div></label>}
function LittleHeader({page,setPage,onSwitch}){return <header className="little-header"><button className="brand little-brand" onClick={()=>setPage('home')}><span className="brand-icon">🪁</span> little mathquest</button><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}><Home size={17}/> Play places</button><button className={page==='studio'?'active':''} onClick={()=>setPage('studio')}><Paintbrush size={17}/> Art studio</button><button className={page==='prizes'?'active':''} onClick={()=>setPage('prizes')}><Sparkles size={17}/> My toy shelf</button><button className={page==='parent'?'active':''} onClick={()=>setPage('parent')}><BarChart3 size={17}/> Grown-ups</button></nav><ProfileChooser active="pranav" onSwitch={onSwitch}/></header>}
export function PreschoolApp({value,onChange,onSwitch,cloudStatus}){const progress=value?.version===1?value:initialPreschool(),[page,setPage]=useState('home'),[worldId,setWorldId]=useState(null),[q,setQ]=useState(null),[round,setRound]=useState(0),[selected,setSelected]=useState(''),[solved,setSolved]=useState(false),[retries,setRetries]=useState(0),[message,setMessage]=useState(''),[celebrate,setCelebrate]=useState(null),[playGoal,setPlayGoal]=useState(6),[voices,setVoices]=useState([]),[voiceName,setVoiceName]=useState(()=>localStorage.getItem('mathquest-voice')||''),started=useRef(Date.now()),session=useRef(Date.now());
 useEffect(()=>{const load=()=>setVoices(englishVoices());load();window.speechSynthesis?.addEventListener?.('voiceschanged',load);return()=>window.speechSynthesis?.removeEventListener?.('voiceschanged',load)},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[page,q?.fingerprint]);useEffect(()=>{if(!celebrate)return;const t=setTimeout(()=>setCelebrate(null),5000);return()=>clearTimeout(t)},[celebrate]);
 const update=fn=>onChange(p=>fn(p?.version===1?p:initialPreschool()));
 const reset=n=>{setQ(n);setSelected('');setSolved(false);setRetries(0);setMessage('');started.current=Date.now();};
 const start=id=>{setWorldId(id);setRound(0);session.current=Date.now();reset(nextLittle(progress,id));setPage('play');};
 const choose=value=>{if(solved)return;setSelected(value);if(String(value)===q.answer){const after=recordLittle(progress,q,{retries,duration:Date.now()-started.current});onChange(after);setSolved(true);setMessage(retries?'You kept trying. You found it!':'You found it!');setCelebrate({icon:'⭐',text:'+5 stars for your toy shelf!'});speakFriendly('You found it!',{voiceName});}else{setRetries(n=>n+1);setMessage('Good try! Let’s look again.');speakFriendly('Good try. Let’s look again.',{voiceName});}};
 const next=()=>{const n=round+1;if(n>=playGoal){update(p=>({...p,sessions:[...p.sessions,{date:Date.now(),worldId,count:playGoal,duration:Date.now()-session.current,completed:true}].slice(-365)}));setCelebrate({icon:'🎉',text:`${playGoal} playful discoveries!`});setPage('done');return;}setRound(n);reset(nextLittle(progress,worldId));};
 const skip=()=>{const after=recordLittle(progress,q,{retries,skipped:true,duration:Date.now()-started.current});onChange(after);const n=round+1;if(n>=playGoal){onChange({...after,sessions:[...after.sessions,{date:Date.now(),worldId,count:playGoal,duration:Date.now()-session.current,completed:true}].slice(-365)});setPage('done')}else{setRound(n);reset(nextLittle(after,worldId));}};
 const buddy=prizes.find(x=>x[0]===progress.rewards?.selected),total=solvedCount(progress);
 return <><LittleHeader page={page} setPage={setPage} onSwitch={onSwitch}/>{celebrate&&<aside className="little-pop" role="status"><span>{celebrate.icon}</span><b>{celebrate.text}</b></aside>}<main className="little-app">{cloudStatus==='connecting'&&<div className="cloud-notice">Getting both children’s saved play…</div>}
 {page==='home'&&<><section className="little-hero"><div><div className="eyebrow">PRANAV’S PLAYFUL LEARNING</div><h1>Tap. Giggle. Discover!</h1><p>Pictures, sounds, praise, and room to try again.</p><label className="little-goal">Activities in this visit <select value={playGoal} onChange={e=>setPlayGoal(+e.target.value)}><option value={4}>4 · quick play</option><option value={6}>6 · playful visit</option><option value={8}>8 · big explorer visit</option></select></label><div className="little-status"><span>{buddy?.[1]||'🐣'}</span><b>{buddy?.[2]||'A new little explorer'}</b><strong>⭐ {stars(progress)}</strong></div></div><div className="little-mascot" aria-hidden="true">🐣<span>1 2 3!</span></div></section><section><div className="section-title"><div className="eyebrow">CHOOSE A PLAY PLACE</div><h2>What sounds fun?</h2><p>Eight places with 40 early-learning skills, plus a free-paint studio.</p></div><div className="little-worlds">{littleWorlds.map(w=><button key={w.id} onClick={()=>start(w.id)} style={{'--little-color':w.color}}><span>{w.icon}</span><div><h3>{w.name}</h3><p>{w.tag}</p><small>{w.skills.filter(s=>progress.skills[s]?.total).length} of {w.skills.length} skills played</small></div><ArrowRight/></button>)}</div></section></>}
 {page==='studio'&&<PaintStudio onHome={()=>setPage('home')}/>}
 {page==='play'&&q&&<section className="little-play"><button className="text-button" onClick={()=>setPage('home')}>← Stop for now</button><div className="little-progress"><b>{littleWorlds.find(w=>w.id===worldId)?.icon} {littleLabels[q.skill]}</b><span>Play {round+1} of {playGoal}</span></div><div className="little-dots">{Array.from({length:playGoal},(_,i)=>i).map(i=><i key={i} className={i<round?'done':i===round?'now':''}/>)}</div><article className="little-card"><button className="listen-button" aria-label="Hear the question" onClick={()=>speakFriendly(q.spoken,{voiceName})}><Volume2/> Hear it</button><h1>{q.prompt}</h1><div className="little-art">{q.art.split('\n').map((x,i)=><React.Fragment key={i}>{x}{i<q.art.split('\n').length-1&&<br/>}</React.Fragment>)}</div><div className="little-answers">{q.choices.map(c=><button key={c} disabled={solved} className={selected===c?(solved?'right':'try'):''} onClick={()=>choose(c)}><span>{q.optionArt?.[c]||c}</span>{q.optionArt?.[c]&&q.optionArt[c]!==c&&<small>{c}</small>}</button>)}</div><p className={`little-message ${solved?'yay':''}`} aria-live="polite">{message}</p>{solved?<button className="primary jumbo" onClick={next}>Next play <ArrowRight/></button>:<button className="text-button" onClick={skip}>Try a different one</button>}</article><p className="little-gentle"><Heart size={18}/> Trying is learning. Help from a grown-up is welcome.</p></section>}
 {page==='done'&&<section className="little-done"><span>🎉</span><h1>Hip hip hooray, Pranav!</h1><p>You played {playGoal} learning games and earned stars.</p><button className="primary jumbo" onClick={()=>start(worldId)}>Play here again</button><button className="secondary" onClick={()=>setPage('home')}>Pick another place</button></section>}
 {page==='prizes'&&<section className="little-prizes"><div className="eyebrow">PRANAV’S TOY SHELF</div><h1>Friends earned through play</h1><p>Every solved activity earns 5 stars, even after trying again. Stars are never taken away for mistakes.</p><strong className="little-wallet">⭐ {stars(progress)} stars</strong><div className="little-prize-grid">{prizes.map(([id,icon,name,cost])=>{const owned=progress.rewards?.owned?.includes(id),chosen=progress.rewards?.selected===id;return <article key={id}><span>{icon}</span><h3>{name}</h3><button className={chosen?'secondary':'primary'} disabled={chosen||(!owned&&stars(progress)<cost)} onClick={()=>update(p=>{if(owned)return {...p,rewards:{...p.rewards,selected:id,updatedAt:Date.now()}};if(stars(p)<cost)return p;return {...p,rewards:{...p.rewards,owned:[...(p.rewards.owned||[]),id],selected:id,updatedAt:Date.now()}}})}>{chosen?'Playing with me':owned?'Choose me':`${cost} ⭐`}</button></article>})}</div></section>}
 {page==='parent'&&<section className="little-parent"><div className="eyebrow">PRANAV · FOR GROWN-UPS</div><h1>Playful progress, kept separate.</h1><p>This profile is designed for short, shared preschool play. These observations are not a developmental assessment.</p><div className="stats"><div><span>Activities solved</span><strong>{total}</strong></div><div><span>Skills encountered</span><strong>{Object.keys(progress.skills).length}<small> / 30</small></strong></div><div><span>Play visits</span><strong>{progress.sessions.length}</strong></div><div><span>Toys collected</span><strong>{progress.rewards?.owned?.length||0}</strong></div></div><div className="parent-note"><Lightbulb/><p>At this age, talking, pointing, moving objects, and getting help are all valuable. Look for comfort and curiosity across several playtimes rather than expecting consistent accuracy.</p></div><section className="voice-setting"><h2>Listening voice</h2><p>Choose a voice installed on this device, then play a sample. Natural or enhanced voices appear first when available.</p><label>Voice <select value={voiceName||preferredVoice(voices)?.name||''} onChange={e=>{setVoiceName(e.target.value);localStorage.setItem('mathquest-voice',e.target.value)}}>{voices.map(v=><option key={`${v.name}-${v.lang}`} value={v.name}>{v.name} · {v.lang}</option>)}</select></label><button className="secondary" onClick={()=>speakFriendly('Hi Pranav! Let’s find something fun to discover.',{voiceName:voiceName||preferredVoice(voices)?.name})}><Volume2 size={17}/> Hear a sample</button>{!voices.length&&<small>Your browser has not reported its installed voices yet.</small>}</section><div className="little-skill-report">{littleWorlds.map(w=><article key={w.id}><h2>{w.icon} {w.name}</h2>{w.skills.map(s=><div key={s}><span>{littleLabels[s]}</span><b>{progress.skills[s]?`${progress.skills[s].independent} solo · ${progress.skills[s].supported} with help`:'Ready to try'}</b></div>)}</article>)}</div><div className="cloud-panel"><b>{cloudStatus==='saved'?'Both profiles backed up to Firebase':'Progress is saved in this browser while cloud backup connects.'}</b><p>Pranav’s activity history and rewards are separate from Shivani’s.</p></div></section>}
 </main><footer><span>🪁 little mathquest</span><p>Play together. Stop while it is still fun.</p><span>Made for Pranav ✦</span></footer></>}
export {ProfileChooser};
