import React,{useEffect,useRef,useState} from 'react';
import {Volume2,ArrowRight,Heart,BarChart3,Home,Sparkles,Lightbulb,Paintbrush,Gamepad2} from 'lucide-react';
import {ageOn} from './child-profile.js';
import {PaintStudio} from './paint-studio.jsx';
import {BalloonKeepy} from './balloon-keepy.jsx';
import {SnakeGarden} from './snake-garden.jsx';
import {PuzzlePlayground} from './puzzle-playground.jsx';
import {ThemePicker,validTheme} from './theme-picker.jsx';
import {englishVoices,speakFriendly} from './speech.js';
import {initialPreschool,littleWorlds,littleLabels,nextLittle,recordLittle} from './preschool-engine.js';
const prizes=[['duck','🦆','Puddle Duck',20],['frog','🐸','Bouncy Frog',30],['dino','🦕','Leafy Dino',45],['lion','🦁','Sunny Lion',60],['rocket','🚀','Zoom Rocket',80],['dragon','🐲','Baby Dragon',100],['robot','🤖','Helpful Robot',120],['unicorn','🦄','Rainbow Unicorn',140],['whale','🐳','Bubble Whale',160],['owl','🦉','Night Owl',180],['monkey','🐵','Jungle Monkey',200],['castle','🏰','Story Castle',220]];
const solvedCount=p=>Object.values(p.skills).reduce((n,s)=>n+s.independent+s.supported,0),spent=p=>prizes.filter(x=>p.rewards?.owned?.includes(x[0])).reduce((n,x)=>n+x[3],0),stars=p=>Math.max(0,solvedCount(p)*5-spent(p));
function ProfileChooser({active,onSwitch,birthDate}){const age=active==='shivani'?ageOn(birthDate):null;return <label className="profile child-switcher"><span>{active==='pranav'?'P':'S'}</span><div><select aria-label="Choose child profile" value={active} onChange={e=>onSwitch(e.target.value)}><option value="shivani">Shivani</option><option value="pranav">Pranav</option></select><small>{active==='pranav'?'Little learner':age===null?'Curious explorer':`Age ${age} · Curious explorer`}</small></div></label>}
function VoicePicker({voices,voiceName,setVoiceName,compact=false}){const choose=value=>{setVoiceName(value);localStorage.setItem('mathquest-voice-v4',value)};return <section className={`voice-setting ${compact?'voice-quick':''}`}><div><h2>Friendly reading voice</h2><p>Warm story recordings guide Pranav’s play. You can turn them off any time.</p></div><label>Voice <select value={voiceName} onChange={e=>choose(e.target.value)}><option value="recorded:flo">Warm story voice · recommended</option><option value="off">Quiet text · no voice</option>{voices.map(v=><option key={`${v.name}-${v.lang}`} value={v.name}>{v.name} · device voice</option>)}</select></label><button className="secondary" disabled={voiceName==='off'} onClick={()=>speakFriendly('Hi Pranav! Let’s find something fun to discover.',{voiceName})}><Volume2 size={17}/> Hear this voice</button><span className="coach-hand" aria-hidden="true">👆</span></section>}
function LittleHeader({page,setPage,onSwitch}){return <header className="little-header"><button className="brand little-brand" onClick={()=>setPage('home')}><span className="brand-icon">🪁</span> Pranav’s Playroom</button><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}><Home size={17}/> Play</button><button className={page==='prizes'?'active':''} onClick={()=>setPage('prizes')}><Sparkles size={17}/> Toys</button><button className={page==='parent'?'active':''} onClick={()=>setPage('parent')}><BarChart3 size={17}/> Grown-ups</button></nav><ProfileChooser active="pranav" onSwitch={onSwitch}/></header>}
function PranavHome({progress,buddy,onPage,onStart}){const games=[['puzzle','🗺️','Maze & Puzzles','maze'],['balloon','🎈','Balloons','sky'],['snake','🐍','Wiggly Snake','garden'],['studio','🎨','Paint','paint']];return <section className="pranav-home"><div className="kid-hero"><div className="kid-hero-copy"><span className="kid-wave">Hi Pranav! 👋</span><h1>What shall we play?</h1><div className="kid-reward"><span>{buddy?.[1]||'🐣'}</span><b>{buddy?.[2]||'Your little buddy'}</b><strong>⭐ {stars(progress)}</strong></div></div><div className="kid-mascot" aria-hidden="true">{buddy?.[1]||'🐣'}<i>✨</i></div></div><div className="game-shelf" aria-label="Big games">{games.map(([id,icon,name,tone])=><button key={id} className={`game-tile ${tone}`} onClick={()=>onPage(id)}><span>{icon}</span><b>{name}</b><i>▶</i></button>)}</div><div className="learning-heading"><span>🌟</span><div><h2>Little learning games</h2><small>Tap any picture</small></div></div><div className="learning-shelf">{littleWorlds.filter(w=>w.id!=='puzzle').map(w=><button key={w.id} onClick={()=>onStart(w.id)} style={{'--little-color':w.color}}><span>{w.icon}</span><b>{w.name.replace(/ (Bay|Parade|Train|Sort|Garden|Town|Cove)$/,'')}</b><div>{w.skills.map(s=><i key={s} className={progress.skills[s]?.total?'played':''}/>)}</div></button>)}</div></section>}
function KidThemes({value,onChange}){return <div className="kid-themes" aria-label="Choose colors">{[['meadow','🌿'],['ocean','🌊'],['sunset','🌅'],['rainbow','🌈'],['space','🚀']].map(([id,icon])=><button key={id} aria-label={`${id} colors`} aria-pressed={value===id} onClick={()=>onChange(id)}>{icon}</button>)}</div>}
export function PreschoolApp({value,onChange,onSwitch,cloudStatus}){const progress=value?.version===1?value:initialPreschool(),[page,setPage]=useState('home'),[worldId,setWorldId]=useState(null),[q,setQ]=useState(null),[round,setRound]=useState(0),[selected,setSelected]=useState(''),[tapCount,setTapCount]=useState(0),[orderPicked,setOrderPicked]=useState([]),[solved,setSolved]=useState(false),[retries,setRetries]=useState(0),[message,setMessage]=useState(''),[celebrate,setCelebrate]=useState(null),[playGoal,setPlayGoal]=useState(6),[voices,setVoices]=useState([]),[voiceName,setVoiceName]=useState(()=>localStorage.getItem('mathquest-voice-v4')||'recorded:flo'),started=useRef(Date.now()),session=useRef(Date.now());
 useEffect(()=>{const load=()=>setVoices(englishVoices());load();window.speechSynthesis?.addEventListener?.('voiceschanged',load);return()=>window.speechSynthesis?.removeEventListener?.('voiceschanged',load)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=validTheme(progress.rewards?.theme);},[progress.rewards?.theme]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[page,q?.fingerprint]);useEffect(()=>{if(!celebrate)return;const t=setTimeout(()=>setCelebrate(null),5000);return()=>clearTimeout(t)},[celebrate]);
 const update=fn=>onChange(p=>fn(p?.version===1?p:initialPreschool()));
 const reset=n=>{setQ(n);setSelected('');setTapCount(0);setOrderPicked([]);setSolved(false);setRetries(0);setMessage('');started.current=Date.now();};
 const start=id=>{setWorldId(id);setRound(0);session.current=Date.now();if(id==='puzzle'){setPage('puzzle');return;}reset(nextLittle(progress,id));setPage('play');};
 const choose=value=>{if(solved)return;setSelected(value);if(String(value)===q.answer){const after=recordLittle(progress,q,{retries,duration:Date.now()-started.current});onChange(after);setSolved(true);setMessage(retries?'You kept trying. You found it!':'You found it!');setCelebrate({icon:'⭐',text:'+5 stars for your toy shelf!'});speakFriendly('You found it!',{voiceName});}else{setRetries(n=>n+1);setMessage('Good try! Let’s look again.');speakFriendly('Good try. Let’s look again.',{voiceName});}};
 const finishTapCount=()=>{const after=recordLittle(progress,q,{retries,duration:Date.now()-started.current});onChange(after);setSolved(true);setMessage('You counted them all!');setCelebrate({icon:'⭐',text:'+5 stars for your toy shelf!'});speakFriendly('You counted them all!',{voiceName});};
 const tapObject=()=>{if(solved)return;const next=tapCount+1;setTapCount(next);if(next===q.target)finishTapCount();else if(next>q.target){setRetries(n=>n+1);setMessage('Let’s count together. Try again.');setTapCount(0);}else{setMessage(`${next}! Keep tapping.`);speakFriendly(String(next),{voiceName});}};
 const finishOrder=nextOrder=>{const after=recordLittle(progress,q,{retries,duration:Date.now()-started.current});onChange(after);setSolved(true);setMessage('You put them in order!');setCelebrate({icon:'⭐',text:'+5 stars for your toy shelf!'});speakFriendly('You put them in order!',{voiceName});};
 const tapOrder=value=>{if(solved)return;const expected=q.order[orderPicked.length];if(value!==expected){setRetries(n=>n+1);setOrderPicked([]);setMessage('Good try. Start the order again.');speakFriendly('Try the order again.',{voiceName});return}const next=[...orderPicked,value];setOrderPicked(next);if(next.length===q.order.length)finishOrder(next);else{setMessage('Nice! Find the next one.');speakFriendly('Find the next one.',{voiceName});}};
 const next=()=>{const n=round+1;if(n>=playGoal){update(p=>({...p,sessions:[...p.sessions,{date:Date.now(),worldId,count:playGoal,duration:Date.now()-session.current,completed:true}].slice(-365)}));setCelebrate({icon:'🎉',text:`${playGoal} playful discoveries!`});setPage('done');return;}setRound(n);reset(nextLittle(progress,worldId));};
 const skip=()=>{const after=recordLittle(progress,q,{retries,skipped:true,duration:Date.now()-started.current});onChange(after);const n=round+1;if(n>=playGoal){onChange({...after,sessions:[...after.sessions,{date:Date.now(),worldId,count:playGoal,duration:Date.now()-session.current,completed:true}].slice(-365)});setPage('done')}else{setRound(n);reset(nextLittle(after,worldId));}};
 const buddy=prizes.find(x=>x[0]===progress.rewards?.selected),total=solvedCount(progress);
 return <><LittleHeader page={page} setPage={setPage} onSwitch={onSwitch}/>{celebrate&&<aside className="little-pop" role="status"><span>{celebrate.icon}</span><b>{celebrate.text}</b></aside>}<main className="little-app">{cloudStatus==='connecting'&&<div className="cloud-notice">Getting both children’s saved play…</div>}
 {page==='home'&&<><PranavHome progress={progress} buddy={buddy} onPage={setPage} onStart={start}/><KidThemes value={progress.rewards?.theme} onChange={theme=>update(p=>({...p,rewards:{...p.rewards,theme,updatedAt:Date.now()}}))}/></>}
 {page==='balloon'&&<BalloonKeepy voiceName={voiceName} onSave={({hits,best,drops})=>update(p=>({...p,balloon:{best:Math.max(p.balloon?.best||0,best),totalTaps:(p.balloon?.totalTaps||0)+hits,drops:(p.balloon?.drops||0)+drops,plays:(p.balloon?.plays||0)+1,updatedAt:Date.now()}}))} onExit={()=>setPage('home')}/>}
 {page==='snake'&&<SnakeGarden voiceName={voiceName} onSave={({pickups,best,snips})=>update(p=>({...p,snake:{best:Math.max(p.snake?.best||8,best),totalPickups:(p.snake?.totalPickups||0)+pickups,snips:(p.snake?.snips||0)+snips,plays:(p.snake?.plays||0)+1,updatedAt:Date.now()}}))} onExit={()=>setPage('home')}/>}
 {page==='studio'&&<PaintStudio onHome={()=>setPage('home')}/>}
 {page==='puzzle'&&<PuzzlePlayground voiceName={voiceName} onRecord={q=>onChange(recordLittle(progress,q,{duration:0}))} onHome={()=>setPage('home')}/>}
 {page==='play'&&q&&<section className="little-play"><button className="text-button" onClick={()=>setPage('home')}>← Stop for now</button><div className="little-progress"><b>{littleWorlds.find(w=>w.id===worldId)?.icon} {littleLabels[q.skill]}</b><span>Play {round+1} of {playGoal}</span></div><div className="little-dots">{Array.from({length:playGoal},(_,i)=>i).map(i=><i key={i} className={i<round?'done':i===round?'now':''}/>)}</div><article className="little-card"><button className="listen-button" aria-label="Hear the question" onClick={()=>speakFriendly(q.spoken,{voiceName})}><Volume2/> Hear it</button><h1>{q.prompt}</h1><div className="little-art">{q.art.split('\n').map((x,i)=><React.Fragment key={i}>{x}{i<q.art.split('\n').length-1&&<br/>}</React.Fragment>)}</div>{q.type==='tapCount'?<div className="tap-count-game"><div className="tap-count-total" aria-live="polite">{tapCount} <small>of {q.target}</small></div><div className="tap-count-items">{Array.from({length:q.target},(_,i)=><button key={i} disabled={solved} className={i<tapCount?'tapped':''} onClick={tapObject} aria-label={`Tap ${i+1}`}>{q.art.split(' ')[0]}</button>)}</div><p className="tap-count-help">Tap each one once 👆</p></div>:q.type==='tapOrder'?<div className="tap-order-game"><div className="tap-order-total" aria-live="polite">{orderPicked.length} <small>of {q.order.length}</small></div><div className="tap-order-items">{q.choices.map(c=><button key={c} disabled={solved} className={orderPicked.includes(c)?'tapped':''} onClick={()=>tapOrder(c)}><span>{q.optionArt?.[c]||c}</span><small>{c}</small></button>)}</div><p className="tap-count-help">Tap the next one 👆</p></div>:<div className="little-answers">{q.choices.map(c=><button key={c} disabled={solved} className={selected===c?(solved?'right':'try'):''} onClick={()=>choose(c)}><span>{q.optionArt?.[c]||c}</span>{q.optionArt?.[c]&&q.optionArt[c]!==c&&<small>{c}</small>}</button>)}</div>}<p className={`little-message ${solved?'yay':''}`} aria-live="polite">{message}</p>{solved?<button className="primary jumbo" onClick={next}>Next play <ArrowRight/></button>:<button className="text-button" onClick={skip}>Try a different one</button>}</article><p className="little-gentle"><Heart size={18}/> Trying is learning. Help from a grown-up is welcome.</p></section>}
 {page==='done'&&<section className="little-done"><span>🎉</span><h1>Hip hip hooray, Pranav!</h1><p>You played {playGoal} learning games and earned stars.</p><button className="primary jumbo" onClick={()=>start(worldId)}>Play here again</button><button className="secondary" onClick={()=>setPage('home')}>Pick another place</button></section>}
 {page==='prizes'&&<section className="little-prizes"><div className="eyebrow">PRANAV’S TOY SHELF</div><h1>Friends earned through play</h1><p>Every solved activity earns 5 stars, even after trying again. Stars are never taken away for mistakes.</p><strong className="little-wallet">⭐ {stars(progress)} stars</strong><div className="little-prize-grid">{prizes.map(([id,icon,name,cost])=>{const owned=progress.rewards?.owned?.includes(id),chosen=progress.rewards?.selected===id;return <article key={id}><span>{icon}</span><h3>{name}</h3><button className={chosen?'secondary':'primary'} disabled={chosen||(!owned&&stars(progress)<cost)} onClick={()=>update(p=>{if(owned)return {...p,rewards:{...p.rewards,selected:id,updatedAt:Date.now()}};if(stars(p)<cost)return p;return {...p,rewards:{...p.rewards,owned:[...(p.rewards.owned||[]),id],selected:id,updatedAt:Date.now()}}})}>{chosen?'Playing with me':owned?'Choose me':`${cost} ⭐`}</button></article>})}</div></section>}
 {page==='parent'&&<section className="little-parent"><div className="eyebrow">PRANAV · FOR GROWN-UPS</div><h1>Playful progress, kept separate.</h1><p>This profile is designed for short, shared preschool play. These observations are not a developmental assessment.</p><div className="stats"><div><span>Activities solved</span><strong>{total}</strong></div><div><span>Skills encountered</span><strong>{Object.keys(progress.skills).length}<small> / 40</small></strong></div><div><span>Balloon taps</span><strong>{progress.balloon?.totalTaps||0}</strong></div><div><span>Best balloon run</span><strong>{progress.balloon?.best||0}</strong></div><div><span>Snake shapes</span><strong>{progress.snake?.totalPickups||0}</strong></div><div><span>Longest snake</span><strong>{progress.snake?.best||8}</strong></div><div><span>Play visits</span><strong>{progress.sessions.length}</strong></div><div><span>Toys collected</span><strong>{progress.rewards?.owned?.length||0}</strong></div></div><div className="parent-note"><Lightbulb/><p>At this age, talking, pointing, moving objects, and getting help are all valuable. Look for comfort and curiosity across several playtimes rather than expecting consistent accuracy.</p></div><VoicePicker voices={voices} voiceName={voiceName} setVoiceName={setVoiceName}/><div className="little-skill-report">{littleWorlds.map(w=><article key={w.id}><h2>{w.icon} {w.name}</h2>{w.skills.map(s=><div key={s}><span>{littleLabels[s]}</span><b>{progress.skills[s]?`${progress.skills[s].independent} solo · ${progress.skills[s].supported} with help`:'Ready to try'}</b></div>)}</article>)}</div><div className="cloud-panel"><b>{cloudStatus==='saved'?'Both profiles backed up to Firebase':'Progress is saved in this browser while cloud backup connects.'}</b><p>Pranav’s activity history and rewards are separate from Shivani’s.</p></div></section>}
 </main><footer><span>🪁 little mathquest</span><p>Play together. Stop while it is still fun.</p><span>Made for Pranav ✦</span></footer></>}
export {ProfileChooser};
