export const littleWorlds=[
 {id:'count',name:'Bubble Count Bay',icon:'🫧',color:'#bde7f2',tag:'Count, touch, and see how many',skills:['count5','count10','numerals','more','tinyAdd']},
 {id:'shape',name:'Shape Parade',icon:'🎈',color:'#ffd7b5',tag:'Meet shapes, colors, and sizes',skills:['shapeMatch','shapeName','colors','sizes','sameDifferent']},
 {id:'pattern',name:'Pattern Train',icon:'🚂',color:'#d9d0f4',tag:'Spot what comes next',skills:['abPattern','abbPattern','copyPattern','sequence','missingPiece']},
 {id:'sort',name:'Picnic Sort',icon:'🧺',color:'#dceab8',tag:'Match and sort playful things',skills:['sortKind','oddOne','matchPair','groups','belongs']},
 {id:'words',name:'Sound Garden',icon:'🌼',color:'#ffe29b',tag:'Play with letters and sounds',skills:['letterMatch','firstSound','rhyme','sameSound','namePicture']},
 {id:'life',name:'Little Helper Town',icon:'🏡',color:'#f6c9d6',tag:'Order, notice, and solve everyday puzzles',skills:['firstLast','beforeAfter','positions','feelings','dailyOrder']},
 {id:'creative',name:'Creative Cove',icon:'🎨',color:'#f7c6ac',tag:'Colors, pictures, and artistic thinking',skills:['colorMix','shapePicture','artPattern','symmetryArt','artCount']},
 {id:'puzzle',name:'Puzzle Playground',icon:'🧩',color:'#bdddd3',tag:'Little clues and spatial puzzles',skills:['matchHome','completePicture','insideOutside','sizeOrder','pictureClue']},
];
export const littleLabels={count5:'Count to 5',count10:'Count to 10',numerals:'Find a number',more:'More and fewer',tinyAdd:'Put small groups together',shapeMatch:'Match a shape',shapeName:'Name a shape',colors:'Match colors',sizes:'Big and small',sameDifferent:'Same and different',abPattern:'AB patterns',abbPattern:'ABB patterns',copyPattern:'Copy a pattern',sequence:'What comes next?',missingPiece:'Find the missing piece',sortKind:'Sort by kind',oddOne:'Which is different?',matchPair:'Find a matching pair',groups:'Make groups',belongs:'What belongs?',letterMatch:'Big and little letters',firstSound:'Beginning sounds',rhyme:'Words that rhyme',sameSound:'Same beginning sound',namePicture:'Name the picture',firstLast:'First and last',beforeAfter:'Before and after',positions:'Where is it?',feelings:'Name a feeling',dailyOrder:'Everyday order',colorMix:'Mix two colors',shapePicture:'Shapes in pictures',artPattern:'Color patterns',symmetryArt:'Mirror pictures',artCount:'Count the art',matchHome:'Match animals and homes',completePicture:'Complete a picture',insideOutside:'Inside and outside',sizeOrder:'Order by size',pictureClue:'Solve a picture clue'};
export function initialPreschool(){return {version:1,skills:{},attempts:[],sessions:[],seen:[],seeds:0,rewards:{owned:[],selected:null,theme:'meadow'},balloon:{best:0,totalTaps:0,drops:0,plays:0,updatedAt:0},snake:{best:8,totalPickups:0,snips:0,plays:0,updatedAt:0},typing:{best:0,totalLetters:0,rounds:0,plays:0,updatedAt:0},first100:{seen:[],correct:{},missed:{},attempts:[],updatedAt:0}};}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const pick=(r,a)=>a[Math.floor(r()*a.length)],shuffle=(r,a)=>[...a].sort(()=>r()-.5),choice=(answer,choices)=>({answer:String(answer),choices:[...new Set(choices.map(String))]});
const countArt=(icon,n)=>Array.from({length:n},()=>icon).join(' ');
/* Distinct-tap counting: tapped holds the indices of already-tapped objects.
 * Re-tapping an object never advances the count (real one-to-one counting). */
export function countTap(tapped,index,target){if(tapped.includes(index))return{tapped,advanced:false,done:false};const next=[...tapped,index];return{tapped:next,advanced:true,done:next.length>=target};}
/* Pattern copying: the tapped tile sequence must reproduce the pattern in order. */
export function copyMatches(pattern,picked){return pattern.length===picked.length&&pattern.every((x,i)=>x===picked[i]);}
/* Symmetry: only the true mirror half completes the picture. */
export function mirrorCompletes(q,candidate){return !!q?.mirror&&candidate===q.mirror.answer;}
export function generateLittle(skill,level,seed){const r=rng(seed),max=level===1?5:10,n=1+Math.floor(r()*max),icons=['🐥','🍓','⭐','🐠','🦋','🚗'],icon=pick(r,icons);let q={skill,seed,type:'choice',level,prompt:'',art:'',answer:'',choices:[]};const set=(prompt,art,answer,choices,spoken=prompt)=>Object.assign(q,{prompt,spoken,art,...choice(answer,shuffle(r,choices))});
 switch(skill){
 case'count5':case'count10':{const cap=skill==='count5'?5:10,k=1+Math.floor(r()*cap);set('How many do you see?',countArt(icon,k),k,[k,Math.max(1,k-1),Math.min(cap,k+1)]);q.type='tapCount';q.target=k;break;}
 case'numerals':{const k=1+Math.floor(r()*10);set(`Can you find number ${k}?`,'🔢',k,[k,(k%10)+1,((k+4)%10)+1]);break;}
 case'more':{const a=1+Math.floor(r()*5),b=a+1+Math.floor(r()*3);q.optionArt={[a]:countArt('🔵',a),[b]:countArt('🟡',b)};set('Which group has more?', 'Look at both groups',b,[a,b]);break;}
 case'tinyAdd':{const a=1+Math.floor(r()*2),b=1+Math.floor(r()*2),sum=a+b;set('How many altogether?',`${countArt('🍎',a)}  +  ${countArt('🍎',b)}`,sum,[sum,Math.max(1,sum-1),sum+1]);break;}
 case'shapeMatch':case'shapeName':{const shapes=[['circle','●'],['square','■'],['triangle','▲'],['star','★']],target=pick(r,shapes);q.optionArt=Object.fromEntries(shapes.map(x=>x));set(skill==='shapeMatch'?`Find the ${target[0]}.`:'What shape is this?',target[1],target[0],shapes.map(x=>x[0]));break;}
 case'colors':{const colors=[['red','🔴'],['blue','🔵'],['yellow','🟡'],['green','🟢']],target=pick(r,colors);q.optionArt=Object.fromEntries(colors);set(`Find ${target[0]}.`,'🎨',target[0],colors.map(x=>x[0]));break;}
 case'sizes':{const big=r()>.5;q.optionArt={big:'🐘',small:'🐭'};set(`Which one is ${big?'big':'small'}?`,'Big or small?',big?'big':'small',['big','small']);break;}
 case'sameDifferent':{const same=r()>.5,a=pick(r,icons),b=same?a:pick(r,icons.filter(x=>x!==a));set('Are these the same or different?',`${a}   ${b}`,same?'same':'different',['same','different']);break;}
 case'abPattern':case'abbPattern':case'sequence':case'missingPiece':{const a=pick(r,icons),b=pick(r,icons.filter(x=>x!==a)),seq=skill==='abbPattern'?[a,b,b,a,b,b]:[a,b,a,b,a,b],cut=skill==='missingPiece'?2:seq.length-1,answer=seq[cut];seq[cut]='❔';q.optionArt={[a]:a,[b]:b};set('What comes next?',seq.join(' '),answer,[a,b,pick(r,icons.filter(x=>x!==a&&x!==b))]);break;}
 case'copyPattern':{const a=pick(r,icons),b=pick(r,icons.filter(x=>x!==a)),c=pick(r,icons.filter(x=>x!==a&&x!==b));let pattern=[];do{pattern=Array.from({length:4},()=>pick(r,[a,b]));}while(!pattern.includes(a)||!pattern.includes(b));const tray=shuffle(r,[a,b,c]);q.type='copySequence';q.pattern=pattern;q.picturesOnly=true;q.optionArt=Object.fromEntries(tray.map(x=>[x,x]));set('Copy the pattern.',pattern.join(' '),pattern.join(''),tray);break;}
 case'sortKind':case'groups':case'belongs':{const sets=[['animals',['🐶','🐱','🐰'],'🚗'],['food',['🍎','🍌','🍓'],'🧦'],['things to wear',['👕','🧢','👟'],'🐟']],setx=pick(r,sets);q.optionArt=Object.fromEntries([...setx[1],setx[2]].map(x=>[x,x]));set(`Put all the ${setx[0]} in the basket.`,'🧺',setx[1][0],[...setx[1],setx[2]],`Which one belongs with ${setx[0]}?`);q.type='pickAll';q.targets=setx[1];break;}
 case'oddOne':{const a=pick(r,icons),b=pick(r,icons.filter(x=>x!==a));q.optionArt={[a]:a,[b]:b};set('Which one is different?',`${a}  ${a}  ${b}`,b,[a,b]);break;}
 case'matchPair':{const a=pick(r,icons),others=icons.filter(x=>x!==a);q.optionArt=Object.fromEntries(icons.map(x=>[x,x]));set('Find the matching picture.',a,a,[a,...shuffle(r,others).slice(0,2)]);break;}
 case'letterMatch':{const letter=pick(r,['A','B','C','M','S','P']);set(`Find the little ${letter}.`,letter,letter.toLowerCase(),[letter.toLowerCase(),...shuffle(r,['a','b','c','m','s','p'].filter(x=>x!==letter.toLowerCase())).slice(0,2)]);break;}
 case'firstSound':case'sameSound':{const sets=[['B',['ball','bear'],'sun','⚽'],['S',['sun','sock'],'ball','☀️'],['M',['moon','mouse'],'cat','🌙'],['P',['pig','pizza'],'dog','🐷']],x=pick(r,sets),ans=x[1][1];const wordArt={ball:'⚽',bear:'🐻',sun:'☀️',sock:'🧦',moon:'🌙',mouse:'🐭',cat:'🐱',pig:'🐷',pizza:'🍕',dog:'🐶'};q.optionArt={[ans]:wordArt[ans],[x[2]]:wordArt[x[2]]};set(skill==='firstSound'?`Which word starts with ${x[0]}?`:`Which starts like ${x[1][0]}?`,x[3],ans,[ans,x[2]]);break;}
 case'rhyme':{const sets=[['cat','hat','sun','🐱'],['log','frog','bee','🪵'],['star','car','fish','⭐']],x=pick(r,sets);q.optionArt={hat:'🎩',sun:'☀️',frog:'🐸',bee:'🐝',car:'🚗',fish:'🐟'};set(`Which word rhymes with ${x[0]}?`,x[3],x[1],[x[1],x[2]]);break;}
 case'namePicture':{const pics=[['dog','🐶'],['apple','🍎'],['moon','🌙'],['fish','🐟']],x=pick(r,pics);q.optionArt=Object.fromEntries(pics.map(y=>y));set('What is this?',x[1],x[0],shuffle(r,pics.map(y=>y[0])).slice(0,3).includes(x[0])?shuffle(r,pics.map(y=>y[0])).slice(0,3):[x[0],...shuffle(r,pics.filter(y=>y[0]!==x[0]).map(y=>y[0])).slice(0,2)]);break;}
 case'firstLast':{const items=['🐛','🐌','🐢'];q.optionArt=Object.fromEntries(items.map(x=>[x,x]));set('Tap them from first to last.',items.join('   '),items[0],items,'Who is first?');q.type='tapOrder';q.order=items;break;}
 case'beforeAfter':case'dailyOrder':{const sets=[['wash hands','eat a snack','🧼','🍎'],['put on socks','put on shoes','🧦','👟'],['plant a seed','see a flower','🌱','🌼']],x=pick(r,sets),hideFirst=r()>.5,hidden=hideFirst?0:1;q.optionArt={[x[0]]:x[2],[x[1]]:x[3]};q.picturesOnly=true;set(hideFirst?'What came first?':'What came next?',`${hideFirst?'❔':x[2]} ➜ ${hideFirst?x[3]:'❔'}`,x[hidden],[x[0],x[1]]);break;}
 case'positions':{const above=r()>.5;set('Where is the bird?',above?'🐦\n🌳':'🌳\n🐦',above?'above':'below',['above','below']);break;}
 case'feelings':{const faces=[['happy','😊'],['sad','😢'],['sleepy','😴'],['surprised','😮']],x=pick(r,faces);q.optionArt=Object.fromEntries(faces.map(y=>y));set('How does this face feel?',x[1],x[0],shuffle(r,faces.map(y=>y[0])).slice(0,3).includes(x[0])?shuffle(r,faces.map(y=>y[0])).slice(0,3):[x[0],...shuffle(r,faces.filter(y=>y[0]!==x[0]).map(y=>y[0])).slice(0,2)]);break;}
 case'colorMix':{const mixes=[['red','yellow','orange','🔴 + 🟡'],['blue','yellow','green','🔵 + 🟡'],['red','blue','purple','🔴 + 🔵']],x=pick(r,mixes);q.optionArt={orange:'🟠',green:'🟢',purple:'🟣'};set('What color can these make?',x[3],x[2],['orange','green','purple']);break;}
 case'shapePicture':{const pics=[['triangle','🏔️'],['circle','☀️'],['square','🪟'],['star','🌟']],x=pick(r,pics);q.optionArt={triangle:'▲',circle:'●',square:'■',star:'★'};set('Which shape do you notice?',x[1],x[0],shuffle(r,pics.map(y=>y[0])).slice(0,3).includes(x[0])?shuffle(r,pics.map(y=>y[0])).slice(0,3):[x[0],...shuffle(r,pics.filter(y=>y[0]!==x[0]).map(y=>y[0])).slice(0,2)]);break;}
 case'artPattern':{const x=pick(r,[['🔴','🔵'],['🟡','🟢'],['🟣','🟠']]);q.optionArt={[x[0]]:x[0],[x[1]]:x[1]};set('Which color comes next?',`${x[0]} ${x[1]} ${x[0]} ${x[1]} ❔`,x[0],[x[0],x[1]]);break;}
 case'symmetryArt':{const pairs=[['◐','◑'],['◑','◐'],['🌓','🌗'],['🌗','🌓']],x=pick(r,pairs),others=pairs.filter(p=>p[0]!==x[0]&&p[1]!==x[1]),wrong=r()>.5?x[0]:pick(r,others)[1];q.optionArt={[x[1]]:x[1],[wrong]:wrong};q.picturesOnly=true;q.mirror={left:x[0],answer:x[1],wrong};set('Which half finishes the picture?',`${x[0]} ┃`,x[1],[x[1],wrong]);break;}
 case'artCount':{const k=2+Math.floor(r()*5);set('How many shapes are in the picture?',countArt(pick(r,['🔺','🔵','🟨']),k),k,[k,Math.max(1,k-1),k+1]);q.type='tapCount';q.target=k;break;}
 case'matchHome':{const homes=[['bird','🪺','🐦'],['rabbit','🕳️','🐰'],['fish','🌊','🐟']],x=pick(r,homes);q.optionArt=Object.fromEntries(homes.map(h=>[h[0],h[1]]));q.picturesOnly=true;set(`Where does the ${x[0]} live?`,x[2],x[0],homes.map(h=>h[0]));break;}
 case'completePicture':{const pics=[['wheel','🚗  +  ❔','door'],['petal','🌼  +  ❔','shoe'],['tail','🐟  +  ❔','hat']],x=pick(r,pics);q.optionArt={wheel:'⭕',petal:'🌸',tail:'〰️',door:'🚪',shoe:'👟',hat:'🎩'};set('Which part completes the picture?',x[1],x[0],[x[0],x[2]]);break;}
 case'insideOutside':{const inside=r()>.5;set('Where is the ball?',inside?'📦⚽':'📦   ⚽',inside?'inside':'outside',['inside','outside']);break;}
 case'sizeOrder':{q.optionArt={small:'🐭',medium:'🐕',big:'🐘'};set('Which one is in the middle size?','🐭   🐕   🐘','medium',['small','medium','big']);break;}
 case'pictureClue':{const clues=[['rain','☁️ + 💧','☀️'],['night','🌙 + ⭐','day'],['birthday','🎂 + 🎈','bedtime']],x=pick(r,clues);q.optionArt={rain:'🌧️',night:'🌙',birthday:'🎂',day:'☀️',bedtime:'🛏️'};set('What is this picture telling us?',x[1],x[0],[x[0],x[2]]);break;}
 default:set('Find the star.','⭐','star',['star','circle']);}
 if(q.type!=='copySequence')q.choices=q.choices.includes(q.answer)?q.choices:[q.answer,...q.choices.slice(0,2)];q.fingerprint=JSON.stringify([skill,q.prompt,q.art,q.answer,q.choices]);return q;}
export function nextLittle(progress,worldId){const world=littleWorlds.find(w=>w.id===worldId),skills=world?world.skills:littleWorlds.flatMap(w=>w.skills),recent=new Set((progress.attempts||[]).slice(-3).map(a=>a.skill));const ranked=[...skills].sort((a,b)=>{const cooldown=(recent.has(a)?1:0)-(recent.has(b)?1:0);return cooldown||((progress.skills[a]?.total||0)-(progress.skills[b]?.total||0));});let seed=progress.seeds||0;for(let i=0;i<2000;i++){seed++;const skill=ranked[i%ranked.length],s=progress.skills[skill],rate=s?.total?s.independent/s.total:0,level=s?.total>=6&&rate>.75?2:1,q=generateLittle(skill,level,seed);if(!progress.seen.includes(q.fingerprint))return {...q,worldId:littleWorlds.find(w=>w.skills.includes(skill)).id};}throw Error('This play place is resting. Pick another one for fresh surprises!');}
export function recordLittle(progress,q,{retries=0,skipped=false,duration=0}={}){if(progress.seen.includes(q.fingerprint))return progress;const a={skill:q.skill,worldId:q.worldId,fingerprint:q.fingerprint,independent:!retries&&!skipped,retries,skipped,duration,date:Date.now()},old=progress.skills[q.skill]||{total:0,independent:0,supported:0,last:0};return {...progress,seeds:Math.max(progress.seeds,q.seed),seen:[...progress.seen,q.fingerprint],attempts:[...progress.attempts,a].slice(-1500),skills:{...progress.skills,[q.skill]:{total:old.total+1,independent:old.independent+(a.independent?1:0),supported:old.supported+(!skipped&&!a.independent?1:0),last:a.date}}};}
function mergeFirst100(a={},b={}){const latest=(b.updatedAt||0)>=(a.updatedAt||0)?b:a,attempts=[...new Map([...(a.attempts||[]),...(b.attempts||[])].map(x=>[`${x.at}|${x.shelf}|${x.word}|${x.correct}`,x])).values()].sort((x,y)=>x.at-y.at).slice(-1000),maxMap=(x={},y={})=>Object.fromEntries([...new Set([...Object.keys(x),...Object.keys(y)])].map(k=>[k,Math.max(x[k]||0,y[k]||0)]));return {...latest,seen:[...new Set([...(a.seen||[]),...(b.seen||[])])],correct:maxMap(a.correct,b.correct),missed:maxMap(a.missed,b.missed),attempts};}
export function mergePreschool(a,b){a=a?.version===1?a:initialPreschool();b=b?.version===1?b:initialPreschool();const ids=new Set(a.attempts.map(x=>x.fingerprint)),added=b.attempts.filter(x=>!ids.has(x.fingerprint));const skills=structuredClone(a.skills);for(const x of added){const old=skills[x.skill]||{total:0,independent:0,supported:0,last:0};skills[x.skill]={total:old.total+1,independent:old.independent+(x.independent?1:0),supported:old.supported+(!x.skipped&&!x.independent?1:0),last:Math.max(old.last,x.date)};}for(const[k,s]of Object.entries(b.skills))if(!skills[k]||s.total>skills[k].total)skills[k]=s;const sessions=[...new Map([...(a.sessions||[]),...(b.sessions||[])].map(x=>[`${x.date}|${x.worldId}`,x])).values()].sort((x,y)=>x.date-y.date).slice(-365);const owned=[...new Set([...(a.rewards?.owned||[]),...(b.rewards?.owned||[])])],latest=(b.rewards?.updatedAt||0)>=(a.rewards?.updatedAt||0)?b.rewards:a.rewards,balloonLatest=(b.balloon?.updatedAt||0)>=(a.balloon?.updatedAt||0)?b.balloon:a.balloon,snakeLatest=(b.snake?.updatedAt||0)>=(a.snake?.updatedAt||0)?b.snake:a.snake,typingLatest=(b.typing?.updatedAt||0)>=(a.typing?.updatedAt||0)?b.typing:a.typing;return {version:1,skills,attempts:[...a.attempts,...added].sort((x,y)=>x.date-y.date).slice(-1500),sessions,seen:[...new Set([...a.seen,...b.seen])],seeds:Math.max(a.seeds||0,b.seeds||0),rewards:{...latest,owned},balloon:balloonLatest||initialPreschool().balloon,snake:snakeLatest||initialPreschool().snake,typing:typingLatest||initialPreschool().typing,first100:mergeFirst100(a.first100,b.first100)};}
