import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,Gamepad2,RotateCcw,Sparkles} from 'lucide-react';
import {makeRunnerLevel,runnerLevels} from './maze-runner-engine.js';

const key=([r,c])=>`${r},${c}`;
const stepMap={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]};

function RunnerMenu({onChoose,onHome,onGames}){return <section className="runner-menu"><button className="text-button runner-back" onClick={onHome}><ArrowLeft/> Adventures</button><div className="runner-sunburst"><span>SHIVANI’S</span><h1>MAZE<br/><em>RUNNER</em></h1><p>Choose your trail. Outsmart the math gates. Reach the portal.</p><div className="runner-menu-buttons">{Object.entries(runnerLevels).map(([id,x])=><button key={id} className={id} onClick={()=>onChoose(id)}><span>{x.icon}</span><div><b>{x.label}</b><small>{x.tag} · {x.gates} math gates</small></div><i>▶</i></button>)}<button className="games" onClick={onGames}><span>🎮</span><div><b>Math workshop</b><small>Build, experiment, and explore</small></div><i>★</i></button></div></div></section>}

function RunnerGame({level,onBack,onSave,onCelebrate}){
 const config=runnerLevels[level],[run,setRun]=useState(()=>makeRunnerLevel(level)),[player,setPlayer]=useState(()=>run.start),[gems,setGems]=useState([]),[answered,setAnswered]=useState([]),[activeGate,setActiveGate]=useState(null),[wrong,setWrong]=useState(false),[done,setDone]=useState(false),[bumps,setBumps]=useState(0),touch=useRef(null),started=useRef(Date.now()),saved=useRef(false);
 const gateMap=useMemo(()=>new Map(run.gates.map(g=>[g.cell,g])),[run]),gemSet=new Set(run.gems),answeredSet=new Set(answered);
 const finish=()=>{if(saved.current)return;saved.current=true;setDone(true);const result={level,gems:gems.length,gates:answered.length,duration:Date.now()-started.current,bumps};onSave(result);onCelebrate({icon:'🏆',title:`${config.label} maze conquered!`,text:`${answered.length} math gates opened · ${gems.length} gems collected.`});};
 const move=direction=>{if(done||activeGate)return;const [dr,dc]=stepMap[direction],next=[player[0]+dr,player[1]+dc],k=key(next);if(!run.open.has(k)){setBumps(n=>n+1);return;}setPlayer(next);if(gemSet.has(k)&&!gems.includes(k))setGems(x=>[...x,k]);const gate=gateMap.get(k);if(gate&&!answeredSet.has(k)){setWrong(false);setActiveGate(gate);return;}if(k===key(run.goal))finish();};
 useEffect(()=>{const onKey=e=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(map[e.key]){e.preventDefault();move(map[e.key]);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
 const swipe=e=>{if(!touch.current)return;const [x,y]=touch.current;touch.current=null;const dx=e.clientX-x,dy=e.clientY-y;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));};
 const answer=value=>{if(value!==activeGate.question.answer){setWrong(true);return;}const cell=activeGate.cell,next=[...answered,cell];setAnswered(next);setActiveGate(null);setWrong(false);if(key(player)===key(run.goal))finish();};
 const restart=()=>{const next=makeRunnerLevel(level);setRun(next);setPlayer(next.start);setGems([]);setAnswered([]);setActiveGate(null);setWrong(false);setDone(false);setBumps(0);saved.current=false;started.current=Date.now();};
 return <section className={`runner-game ${level}`}><div className="runner-game-top"><button className="text-button" onClick={onBack}><ArrowLeft/> Levels</button><div><b>{config.icon} {config.label} run</b><span>💎 {gems.length}/{run.gems.length}</span><span>🔓 {answered.length}/{run.gates.length}</span></div><button className="secondary" onClick={restart}><RotateCcw/> New maze</button></div><div className="runner-stage"><div className="runner-story"><span className="runner-avatar">{config.icon}</span><div><span className="eyebrow">THE PORTAL IS OPENING</span><h1>Find your way through!</h1><p>Collect gems and solve every glowing math gate.</p></div></div><div className="runner-board" style={{'--runner-size':run.size}} onPointerDown={e=>{touch.current=[e.clientX,e.clientY]}} onPointerUp={swipe} aria-label={`${config.label} maze runner board`}>{Array.from({length:run.size*run.size},(_,i)=>{const r=Math.floor(i/run.size),c=i%run.size,k=`${r},${c}`,open=run.open.has(k),here=player[0]===r&&player[1]===c,goal=run.goal[0]===r&&run.goal[1]===c,gate=gateMap.has(k)&&!answeredSet.has(k),gem=gemSet.has(k)&&!gems.includes(k);return <button key={k} disabled={!open||done||!!activeGate} className={`runner-cell ${open?'road':'wall'} ${here?'here':''} ${goal?'portal':''} ${gate?'gate':''}`} onClick={()=>{const dr=r-player[0],dc=c-player[1];if(Math.abs(dr)+Math.abs(dc)===1)move(dr<0?'up':dr>0?'down':dc<0?'left':'right')}} aria-label={here?'Shivani runner':goal?'Finish portal':gate?'Math gate':gem?'Gem':open?'Open path':'Wall'}>{here?config.icon:goal?'🌀':gate?'🔒':gem?'💎':''}</button>})}</div><div className="runner-controls"><button aria-label="Move up" onClick={()=>move('up')}>▲</button><div><button aria-label="Move left" onClick={()=>move('left')}>◀</button><button aria-label="Move down" onClick={()=>move('down')}>▼</button><button aria-label="Move right" onClick={()=>move('right')}>▶</button></div><p>Swipe the maze, tap the next path, or use the pad.</p></div></div>{activeGate&&<div className="math-gate-backdrop"><section className="math-gate" role="dialog" aria-modal="true" aria-labelledby="gate-title"><span>🔐</span><div className="eyebrow">MATH GATE</div><h2 id="gate-title">{activeGate.question.prompt} = ?</h2><p>Choose the key that opens this gate.</p><div>{activeGate.question.choices.map(x=><button key={x} onClick={()=>answer(x)}>{x}</button>)}</div>{wrong&&<strong>Almost—try another key.</strong>}</section></div>}{done&&<div className="runner-finish"><section><span>🏆</span><h2>Maze conquered!</h2><p>You opened {answered.length} math gates and collected {gems.length} gems.</p><button className="primary" onClick={restart}>Run another {config.label.toLowerCase()} maze</button><button className="secondary" onClick={onBack}>Choose a new level</button></section></div>}</section>;
}

export function ShivaniMazeRunner({onHome,onGames,onSave,onCelebrate}){const[level,setLevel]=useState(null);return level?<RunnerGame level={level} onBack={()=>setLevel(null)} onSave={onSave} onCelebrate={onCelebrate}/>:<RunnerMenu onChoose={setLevel} onHome={onHome} onGames={onGames}/>;}
