import React,{useMemo,useState} from 'react';
import {ArrowLeft,RefreshCw,Sparkles} from 'lucide-react';
import {makeMathTrail,trailModes} from './math-trails-engine.js';

const descriptions={count:'Find every number in counting order.',skip:'Hop by 2s, 3s, 5s, or 10s.',times:'Follow one multiplication table.',fractions:'Move from smaller parts toward one whole.',money:'Follow the coin totals in order.',time:'Follow the clocks fifteen minutes at a time.'};
function ArcadeMenu({onChoose,onHome,onRunner}){return <section className="arcade-page"><button className="text-button" onClick={onHome}><ArrowLeft/> Adventures</button><div className="arcade-hero"><span>🎪</span><div><div className="eyebrow">SHIVANI’S MATH GAMES</div><h1>Pick a playful trail</h1><p>Every board changes. Follow the hidden math path from one friend to another.</p></div><button className="secondary" onClick={onRunner}>🦊 Maze Runner</button></div><div className="arcade-grid">{Object.entries(trailModes).map(([id,x],i)=><button key={id} className={`arcade-card game-${i+1}`} onClick={()=>onChoose(id)}><span>{x.start}</span><i>{x.icon}</i><div><h2>{x.name}</h2><p>{descriptions[id]}</p><b>PLAY ▶</b></div><em>{x.goal}</em></button>)}</div><div className="arcade-note"><Sparkles/><p>Six game families create unlimited fresh boards. There are no timers and mistakes never remove points.</p></div></section>}

function TrailGame({mode,onBack,onSave}){const[round,setRound]=useState(1),[game,setGame]=useState(()=>makeMathTrail(mode)),[step,setStep]=useState(0),[wrong,setWrong]=useState(null),[done,setDone]=useState(false),[tries,setTries]=useState(0),started=useMemo(()=>Date.now(),[round]);const completed=new Set(game.path.slice(0,step).map(x=>x.join(','))),nextCell=game.path[step]?.join(',');const choose=cell=>{if(done)return;const k=`${cell.r},${cell.c}`;if(k!==nextCell){setWrong(k);setTries(n=>n+1);setTimeout(()=>setWrong(null),450);return;}const next=step+1;setStep(next);setWrong(null);if(next===game.sequence.length){setDone(true);onSave({mode,round,duration:Date.now()-started,tries});}};const fresh=()=>{setRound(n=>n+1);setGame(makeMathTrail(mode));setStep(0);setWrong(null);setDone(false);setTries(0);};return <section className={`trail-game trail-${mode}`}><div className="trail-game-top"><button className="text-button" onClick={onBack}><ArrowLeft/> All games</button><div><span>{game.start}</span><b>{game.name}</b><span>{game.goal}</span></div><button className="secondary" onClick={fresh}><RefreshCw/> New board</button></div><div className="worksheet"><div className="worksheet-title"><div><span className="eyebrow">FRESH BOARD {round}</span><h1>{descriptions[mode]}</h1></div><div className="trail-score"><b>{step}</b><small>of 8 found</small></div></div><div className="worksheet-board" style={{'--trail-size':game.size}}>{game.cells.map(cell=>{const k=`${cell.r},${cell.c}`,isDone=completed.has(k),isNext=k===nextCell,isStart=cell.routeIndex===0,isGoal=cell.routeIndex===game.sequence.length-1;return <button key={k} onClick={()=>choose(cell)} className={`${isDone?'found':''} ${wrong===k?'wrong':''} ${isNext&&step===0?'first':''}`} aria-label={`${cell.label}${isStart?' start':''}${isGoal?' finish':''}`}><span>{cell.label}</span>{isStart&&<i>{game.start}</i>}{isGoal&&<i>{game.goal}</i>}</button>})}</div><div className="trail-strip"><span>{game.start}</span>{game.sequence.map((x,i)=><i key={x.label} className={i<step?'done':i===step?'now':''}>{i<step?'✓':x.label}</i>)}<span>{game.goal}</span></div>{!done&&<p className="trail-coach">{step===0?'👆 Start beside '+game.start:`Great path! Now find ${game.sequence[step]?.label}.`}</p>}{done&&<div className="trail-win"><span>🎉</span><div><h2>Trail complete!</h2><p>You discovered all eight steps.</p></div><button className="primary" onClick={fresh}>Play a new board</button></div>}</div></section>}

export function ShivaniGameArcade({onHome,onRunner,onSave}){const[mode,setMode]=useState(null);return mode?<TrailGame mode={mode} onBack={()=>setMode(null)} onSave={onSave}/>:<ArcadeMenu onChoose={setMode} onHome={onHome} onRunner={onRunner}/>;}
