import React,{useMemo,useState} from 'react';
import {ArrowLeft,RefreshCw,Sparkles,Shuffle} from 'lucide-react';
import {makeMathTrail,trailModes} from './math-trails-engine.js';

const descriptions={count:'Find every number in counting order.',skip:'Hop by 2s, 3s, 5s, or 10s.',times:'Follow one multiplication table.',fractions:'Move from smaller parts toward one whole.',money:'Follow the coin totals in order.',time:'Follow the clocks fifteen minutes at a time.'};
const prizes={count:['☁️','Cloud Crown'],skip:['👑','Lily-Pad Legend'],times:['🦋','Garden Genius'],fractions:['🌺','Fraction Flower'],money:['💰','Treasure Finder'],time:['🌈','Rainbow Rescuer']};
const cheers=['Nice move!','Great spotting!','Path power!','You found it!','Brilliant!','Keep going!'];
const randomMode=except=>{const ids=Object.keys(trailModes).filter(x=>x!==except);return ids[Math.floor(Math.random()*ids.length)];};
function ding(big=false){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(big?523:440,c.currentTime);o.frequency.exponentialRampToValueAtTime(big?1046:660,c.currentTime+.16);g.gain.setValueAtTime(.055,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.23);}catch{}}

function ArcadeMenu({onChoose,onHome,onRunner}){return <section className="arcade-page"><button className="text-button" onClick={onHome}><ArrowLeft/> Adventures</button><div className="arcade-hero"><span>🎪</span><div><div className="eyebrow">SHIVANI’S MATH GAMES</div><h1>Pick a playful trail</h1><p>Every board changes. Follow the hidden math path from one friend to another.</p></div><div className="arcade-hero-actions"><button className="primary" onClick={()=>onChoose(randomMode())}><Shuffle/> Surprise me!</button><button className="secondary" onClick={onRunner}>🦊 Maze Runner</button></div></div><div className="arcade-grid">{Object.entries(trailModes).map(([id,x],i)=><button key={id} className={`arcade-card game-${i+1}`} onClick={()=>onChoose(id)}><span>{x.start}</span><i>{x.icon}</i><div><h2>{x.name}</h2><p>{descriptions[id]}</p><b>PLAY ▶</b></div><em>{x.goal}</em></button>)}</div><div className="arcade-note"><Sparkles/><p>Six game families create unlimited fresh boards. There are no timers and mistakes never remove points.</p></div></section>}

function TrailGame({mode,onBack,onSave,onDifferent}){
 const[round,setRound]=useState(1),[game,setGame]=useState(()=>makeMathTrail(mode)),[step,setStep]=useState(0),[wrong,setWrong]=useState(null),[done,setDone]=useState(false),[tries,setTries]=useState(0),[pop,setPop]=useState(null),[cheer,setCheer]=useState('Find the first step!'),started=useMemo(()=>Date.now(),[round]);
 const completed=new Set(game.path.slice(0,step).map(x=>x.join(','))),nextCell=game.path[step]?.join(','),runnerCell=step?game.path[step-1]?.join(','):null,[prizeIcon,prizeName]=prizes[mode];
 const choose=cell=>{if(done)return;const k=`${cell.r},${cell.c}`;if(k!==nextCell){setWrong(k);setTries(n=>n+1);setCheer('That is a side path—look nearby!');setTimeout(()=>setWrong(null),450);return;}const next=step+1;setStep(next);setWrong(null);setPop({cell:k,icon:['✨','⭐','💫','🌟'][next%4]});setCheer(cheers[next%cheers.length]);ding(next===game.sequence.length);setTimeout(()=>setPop(null),650);if(next===game.sequence.length){setDone(true);onSave({mode,round,duration:Date.now()-started,tries});}};
 const fresh=()=>{setRound(n=>n+1);setGame(makeMathTrail(mode));setStep(0);setWrong(null);setDone(false);setTries(0);setPop(null);setCheer('Find the first step!');};
 return <section className={`trail-game trail-${mode}`}><div className="trail-game-top"><button className="text-button" onClick={onBack}><ArrowLeft/> All games</button><div><span>{game.start}</span><b>{game.name}</b><span>{game.goal}</span></div><button className="secondary" onClick={fresh}><RefreshCw/> New board</button></div><div className="worksheet"><div className="worksheet-title"><div><span className="eyebrow">FRESH BOARD {round}</span><h1>{descriptions[mode]}</h1></div><div className="trail-score"><b>{step}</b><small>of 8 found</small>{step>=2&&!done&&<em>🔥 {step} streak</em>}</div></div><div className="worksheet-board" style={{'--trail-size':game.size}}>{game.cells.map(cell=>{const k=`${cell.r},${cell.c}`,isDone=completed.has(k),isNext=k===nextCell,isStart=cell.routeIndex===0,isGoal=cell.routeIndex===game.sequence.length-1;return <button key={k} onClick={()=>choose(cell)} className={`${isDone?'found':''} ${wrong===k?'wrong':''} ${isNext&&step===0?'first':''}`} aria-label={`${cell.label}${isStart?' start':''}${isGoal?' finish':''}`}><span>{cell.label}</span>{isStart&&step===0&&<i>{game.start}</i>}{isGoal&&<i>{game.goal}</i>}{runnerCell===k&&!done&&<i className="trail-runner">{game.start}</i>}{pop?.cell===k&&<strong className="trail-pop">{pop.icon}</strong>}</button>})}</div><div className="trail-strip"><span>{game.start}</span>{game.sequence.map((x,i)=><i key={x.label} className={i<step?'done':i===step?'now':''}>{i<step?'✓':x.label}</i>)}<span>{game.goal}</span></div>{!done&&<p className="trail-coach">{step===0?'👆 Start beside '+game.start:`${cheer} Now find ${game.sequence[step]?.label}.`}</p>}{done&&<div className="trail-win"><div className="mini-confetti" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i}>★</i>)}</div><span>{prizeIcon}</span><div><small>NEW ROUND BADGE</small><h2>{prizeName}!</h2><p>Eight discoveries. One complete trail.</p></div><div className="trail-win-actions"><button className="primary" onClick={fresh}>Another board</button><button className="secondary" onClick={onDifferent}><Shuffle/> Surprise game</button></div></div>}</div></section>;
}

export function ShivaniGameArcade({onHome,onRunner,onSave}){const[mode,setMode]=useState(null);return mode?<TrailGame key={mode} mode={mode} onBack={()=>setMode(null)} onSave={onSave} onDifferent={()=>setMode(randomMode(mode))}/>:<ArcadeMenu onChoose={setMode} onHome={onHome} onRunner={onRunner}/>;}
