import {naturalVoiceClips} from './natural-voice-clips.js';

const bad=/compact|espeak|festival|fred|whisper|zarvox|trinoids|cellos|bells/i;
export function voiceScore(v){const name=v.name||'',lang=(v.lang||'').toLowerCase();if(!lang.startsWith('en')||bad.test(name))return-1000;let score=0;if(/premium|enhanced|natural|neural|online/i.test(name))score+=100;if(/flo|sandy|shelley|eddy|reed|rocko|ava|samantha|allison|susan|karen|moira|serena|aria|jenny|sonia|libby/i.test(name))score+=55;if(lang==='en-us')score+=25;else if(lang==='en-gb'||lang==='en-au'||lang==='en-ie')score+=18;if(v.localService)score+=8;if(v.default)score+=3;return score;}
export function englishVoices(synth=window.speechSynthesis){return synth?.getVoices?.().filter(v=>voiceScore(v)>-1000).sort((a,b)=>voiceScore(b)-voiceScore(a))||[];}
export function preferredVoice(voices=englishVoices(),saved=localStorage.getItem('mathquest-voice')){return voices.find(v=>v.name===saved)||voices[0]||null;}
let activeAudio=null;
function speakDevice(text,{voiceName,rate}){if(!('speechSynthesis'in window))return;const synth=window.speechSynthesis;synth.cancel();const u=new SpeechSynthesisUtterance(text),voice=preferredVoice(englishVoices(synth),voiceName);if(voice){u.voice=voice;u.lang=voice.lang;}else u.lang='en-US';u.rate=rate;u.pitch=1;synth.speak(u);}
export function speakFriendly(text,{voiceName='recorded:flo',rate=.9}={}){window.speechSynthesis?.cancel();if(activeAudio){activeAudio.pause();activeAudio=null}const clip=voiceName==='recorded:flo'&&naturalVoiceClips[text];if(clip&&typeof Audio!=='undefined'){const audio=new Audio(clip);activeAudio=audio;audio.addEventListener('ended',()=>{if(activeAudio===audio)activeAudio=null},{once:true});audio.play().catch(()=>speakDevice(text,{voiceName:null,rate}));return audio}speakDevice(text,{voiceName:voiceName==='recorded:flo'?null:voiceName,rate});}
